create or replace table DE_LESNI_SCRAPE as
SELECT 
  KOD_BUNDESLAND, 
  BUNDESLAND, 
  JMENO, 
  ADRESA,
  CASE   
    WHEN TRY_CAST(LEFT(KONTAKT, 5) AS INTEGER) IS NOT NULL AND SUBSTRING(KONTAKT, 6, 1) = ' '
      THEN LTRIM(SUBSTRING(KONTAKT, 7)) 
    ELSE KONTAKT
  END AS MESTO,
   CASE 
    WHEN TRY_CAST(LEFT(KONTAKT, 5) AS INTEGER) IS NOT NULL AND SUBSTRING(KONTAKT, 6, 1) = ' '
      THEN LEFT(KONTAKT, 5)
    ELSE NULL   
  END AS PSC,  
  LATITUDE, 
  LONGITUDE, 
  CZ_DE
FROM 
"DE_lesni_scrape";